// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC01RbvPaWMobuTmSN9fwl9DBEPSMRmBw4',
    appId: '1:174317304268:web:e3f10ab3e775d51d2bc569',
    messagingSenderId: '174317304268',
    projectId: 'campusassist-a472a',
    authDomain: 'campusassist-a472a.firebaseapp.com',
    storageBucket: 'campusassist-a472a.appspot.com',
    measurementId: 'G-B1YR1C99VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBrVdBh7Am728Z6YEJEtXQeZ1-FQgwivs',
    appId: '1:174317304268:android:426dbaf32a0114012bc569',
    messagingSenderId: '174317304268',
    projectId: 'campusassist-a472a',
    storageBucket: 'campusassist-a472a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxOy3Ca2pfRbma0HmI3JbVdWblgqMSWxM',
    appId: '1:174317304268:ios:05afd6de0d4769d52bc569',
    messagingSenderId: '174317304268',
    projectId: 'campusassist-a472a',
    storageBucket: 'campusassist-a472a.appspot.com',
    iosClientId: '174317304268-j0aaiu7e7h37n5k2ov8njssot4nremb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.campus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxOy3Ca2pfRbma0HmI3JbVdWblgqMSWxM',
    appId: '1:174317304268:ios:05afd6de0d4769d52bc569',
    messagingSenderId: '174317304268',
    projectId: 'campusassist-a472a',
    storageBucket: 'campusassist-a472a.appspot.com',
    iosClientId: '174317304268-j0aaiu7e7h37n5k2ov8njssot4nremb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.campus',
  );
}
